PokeTradeV1/pokeTrade/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='cart.index'),
    path('<int:id>/add/', views.add, name='cart.add'),
    path('clear/', views.clear, name='cart.clear'),
    path('purchase/', views.purchase, name='cart.purchase'),
]

PokeTradeV1/pokeTrade/friends_page/urls.py
from django.urls import path
from . import views

app_name = "friends_page"

urlpatterns = [
    path('', views.index, name='index'),
    path('add_friend/<int:id>/', views.add_friend, name='add_friend'),
]

PokeTradeV1/pokeTrade/pokeTrade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home import views

urlpatterns = [
    path('', views.index, name='pokemons.index'),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('pokemons/', include('pokemons.urls')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('friends_page/', include('friends_page.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

PokeTradeV1/pokeTrade/pokeTrade/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{{ template_data.title }}</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body style="font-family: 'Poppins', sans-serif;">

  <!-- Header -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-success p-3 shadow-sm">
    <div class="container">
      <a class="navbar-brand d-flex align-items-center" href="{% url 'home.index' %}">
        <img src="{% static 'img/logo.png' %}" alt="logo" height="40" class="me-2" />
        <strong>Poke Store</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
          <a class="nav-link text-white" href="{% url 'home.about' %}">About</a>
          <a class="nav-link text-white" href="{% url 'pokemons.index' %}">Marketplace</a>
          <a class="nav-link text-white" href="{% url 'cart.index' %}">Cart</a>
            <a class="nav-link" href="{% url 'friends_page:index' %}">Friends</a>
          {% if user.is_authenticated %}
          <a class="nav-link text-white" href="{% url 'accounts.orders' %}">Orders</a>
          <a class="nav-link text-white" href="{% url 'accounts.logout' %}">Logout ({{ user.username }})</a>
          <a class="nav-link text-white" href="{% url 'accounts.profile' %}">Profile</a>
          {% else %}
          <a class="nav-link text-white" href="{% url 'accounts.login' %}">Login</a>
          <a class="nav-link text-white" href="{% url 'accounts.signup' %}">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

  <!-- Main  -->
  <main class="py-4">
    {% block content %}{% endblock content %}
  </main>

  <!-- Foot -->
  <footer class="bg-light text-dark pt-5">
    <div class="container">
      <div class="row text-center text-md-start">
        <div class="col-md-6 mb-4">
          <h5 class="text-success">Poke Store</h5>
          <hr class="border-success" />
          <p>
            Welcome to Poke Store — your one-stop digital shop for Pokémon adventures. Collect, and explore effortlessly with our intuitive platform.
          </p>
        </div>
        <div class="col-md-3 mb-4">
          <h5 class="text-success">Links</h5>
          <hr class="border-success" />
          <ul class="list-unstyled">
            <li><a class="text-dark" href="{% url 'home.about' %}">About</a></li>
            <li><a class="text-dark" href="{% url 'pokemons.index' %}">Pokémons</a></li>
            <li><a class="text-dark" href="{% url 'cart.index' %}">Cart</a></li>
          </ul>
        </div>
        <div class="col-md-3 mb-4">
          <h5 class="text-success">Contact</h5>
          <hr class="border-success" />
          <p><i class="fas fa-home me-2"></i> Atlanta, Georgia</p>
          <p><i class="fas fa-envelope me-2"></i> info@pokemons.com</p>
          <p><i class="fas fa-phone me-2"></i> +81 03-3333-3333</p>
        </div>
      </div>
    </div>
    <div class="bg-success text-white text-center py-3 mt-4">
    </div>
  </footer>
</body>